### ISSUE TITLE
Ability to list existing tickets

### ISSUE THREAD

**Issue by wdanilo** [textbook/atom-tracker#1]
Hello! It would be awesome to be able to list available tickets and inform pivotal tracker about the work start from within atom. Is such feature on the roadmap?

**Comment by textbook** [comment]
That feature is already implemented (https://www.pivotaltracker.com/story/show/112670207); you get a drop-down list of the stories ready to start and can pick one to begin. As an example, see the first GIF in the README. Or is that not what you mean?

**Comment by textbook** [comment]
I assume that this is no longer needed - ping me if I'm wrong!
